language: python
python:
  - "2.7"
branches:
  only:
  - dev
cache:
  pip: true
  directories:
  - "${HOME}/bin"
addons:
  apt:
    packages:
    - jq
env:
  global:
    - PATH="${HOME}/bin:${PATH}"
    - TMPDIR="${TMPDIR:-/tmp}"
    - TERRAFORM_VERSION="0.10.7"
    - HELM_VERSION="v2.6.2"
    - JQ_VERSION="1.5"
    - KUBECONFIG="${TRAVIS_BUILD_DIR}/artifacts/admin.conf"
    - TERRAFORM_DIR="${TRAVIS_BUILD_DIR}/contrib/terraform/openstack"
    - TERRAFORM_VARS="variables.tfvars"
    - ANSIBLE_USER="core"
    - ANSIBLE_INVENTORY="${TERRAFORM_DIR}/openstack.py"
    - TF_VAR_public_key_path="${TRAVIS_BUILD_DIR}/automation.pub"
    - SSH_PRIVATE_KEY_PATH="${TRAVIS_BUILD_DIR}/automation.key"
before_install:
  - openssl aes-256-cbc -K $encrypted_70983d80ce75_key -iv $encrypted_70983d80ce75_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - eval $(ssh-agent -s)
  - chmod 600 ${SSH_PRIVATE_KEY_PATH}
  - ssh-add ${SSH_PRIVATE_KEY_PATH}
  - source openrc
install:
  - pip install -U ansible jinja2 python-openstackclient shade ;
    ansible --version
  - if ! terraform version ; then
      pushd "${TMPDIR}" ;
      curl -sSL
        -o terraform.zip
        "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" ;
      unzip terraform.zip ;
      mv -v terraform "${HOME}/bin/terraform" ;
      chmod +x "${HOME}/bin/terraform" ;
      popd ;
      terraform version ;
    fi
  - if ! helm version --client ; then
      push "${TMPDIR}" ;
      wget -qO- "https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz" | tar xvz --strip-components=1 ;
      mv -v helm "${HOME}/bin/helm" ;
      chmod +x "${HOME}/bin/helm" ;
      popd ;
      helm version --client ;
    fi
  - if ! kubectl version --client ; then
      push "${TMPDIR}" ;
      curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl ;
      mv -v kubectl "${HOME}/bin/kubectl" ;
      chmod +x "${HOME}/bin/kubectl" ;
      popd ;
      kubectl version --client ;
    fi
  - if ! jq --version ; then
      push "${TMPDIR}" ;
      curl -sSL
      -o jq
      "https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64"
      mv -v jq "${HOME}/bin/jq" ;
      chmod +x "${HOME}/bin/kubectl" ;
      popd ;
      jq --version ;
    fi
script:
  - pushd "${TERRAFORM_DIR}";
    ${ANSIBLE_INVENTORY} --refresh --list
  - if [[ ${TRAVIS_COMMIT_MESSAGE} != *"skipterra"* ]] ; then
      terraform init -force-copy -get=true -get-plugins=true ;
      terraform apply -var-file ${TERRAFORM_VARS} -auto-approve=true ;
      ${ANSIBLE_INVENTORY} --refresh --list ;
    fi
  - popd
  - if [[ ${TRAVIS_COMMIT_MESSAGE} != *"skipansible"* ]] ; then
      ansible-playbook -i ${ANSIBLE_INVENTORY} wait_ssh.yml -e ansible_user=${ANSIBLE_USER} ;
    fi
  - if [[ ${TRAVIS_COMMIT_MESSAGE} != *"skipansible"* ]] ; then
      ansible-playbook -i ${ANSIBLE_INVENTORY} cluster.yml -b -e ansible_user=${ANSIBLE_USER} ;
    fi
  - if [ ! -f ${KUBECONFIG} ]; then
      ansible -b -m fetch
              -a "src=/etc/kubernetes/admin.conf dest=${KUBECONFIG} flat=yes"
              -i ${ANSIBLE_INVENTORY}
              -e 'ansible_user=core'
              -e 'ansible_python_interpreter=/opt/bin/python'
              '*master-1*' ;
    fi
  - sed -i -r 's/(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'/$(${ANSIBLE_INVENTORY} --refresh --list | jq -r '."kube-master"[0] as $master | ._meta.hostvars[$master].openstack.public_v4')/ ${KUBECONFIG}
  - "sed -i -e 's/certificate-authority-data.*/insecure-skip-tls-verify: true/' ${KUBECONFIG}"
  - kubectl version
  - helm version
  - kubectl get nodes -o wide
